<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

use App\Models\Book;
use App\Models\Author;
use App\Models\Category;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                
                // http://localhost:8000/storage/pdfs/Friends_compressed.pdf  URL
                // http://localhost:8000/cover_images/Friends.jpg 
                // http://localhost:8000/user_photos/Friends.jpg 

              //  'book_name' => 'الأصدقاء والغول',
                'book_name' => 'Friends and ghouls',
                'cover_image' => '/cover_images/Friends.jpg',
            //    'abstract' => '.هو كتاب أطفال يحكي قصة مغامرة يخوضها مجموعة من الأصدقاء الصغار الذين يواجهون غولًا أو وحشًا في قصتهم',
                'abstract' => 'It is a childrens book that tells the story of an adventure undertaken by a group of young friends who encounter a ghoul or monster in their story.', 
                'pdf' => Storage::url('pdfs/Friends_compressed.pdf'),
           //     'author_name' => 'محاسن جادو',
                'author_name' => 'Mahasen Jado',
                'category_name' => 'أطفال',
                'category_name_en' => 'Children',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            //    'book_name' => 'ليلى والذئب',
                'book_name' => 'Laila and the Wolf',
                'cover_image' => '/cover_images/laila.jpg',
           //     'abstract' =>  '.إنها قصة الفتاة ليلى التي أرسلتها والدتها بكعك طازج الى منزل جدتها و في طريقها ظهر الذئب الماكر',
                'abstract' => 'It is the story of the girl Laila whose mother sent her with fresh cakes to her grandmother’s house, and on her way the cunning wolf appeared.',
                'pdf' => Storage::url('pdfs/laila_compressed.pdf'),
          //      'author_name' => 'كامل كيلاني',
                'author_name' => 'Kamel Kilani',
                'category_name' => 'أطفال',
                'category_name_en' => 'Children',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [                
            //    'book_name' => 'ذات الرداء الأخضر',
                'book_name' => 'Girl with the green scarf',
                'cover_image' => '/cover_images/green.jpg',
          //      'abstract' => '.قصة الفتاة ذات الرداء الأخضر ',
                'abstract' => 'The story of the girl in Green scarf.',
                'pdf' => Storage::url('pdfs/Green_compressed.pdf'),
            //    'author_name' => 'محاسن جادو',
                'author_name' => 'Mahasen Jado',
                'category_name' => 'أطفال',
                'category_name_en' => 'Children',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
              //  'book_name' => 'حفرة الذئاب',
                'book_name' => 'Wolf hole',
                'cover_image' => '/cover_images/hofraz.jpg',
            //    'abstract' => 'تدور أحداث القصة عن «أنابِل»، الفتاة الصغيرة التي تعيش في ريف بنسلفانيا إبَّان الحرب العالمية الثانية، حيث تحكي عن الانقلاب الذي طرأ على حياتها بسببِ فتاةٍ مؤذِية عنيدة في منزل جيرانها، ورجلٍ متشرِّد غريب الأطوار؛ وعن اضطرارها إلى الكذب وكتمان بعض الأسرار عن أسرتها بسبب مواقف معقَّدة تمر بها',
                'abstract' => 'The story revolves around “Annabel,” a young girl living in rural Pennsylvania during World War II. She tells of the upheaval that occurred in her life because of a mischievous, stubborn girl in her neighbors’ house, and an eccentric homeless man. About her having to lie and keep some secrets from her family because of complicated situations',
                'pdf' => Storage::url('pdfs/Wolf_hole.pdf'),
              //  'author_name' => 'لورين ووك',
                'author_name' => 'Lauren Walk',
                'category_name' => 'أطفال',
                'category_name_en' => 'Children',
                'created_at' => now(),
                'updated_at' => now(),
            ],  
            [          
             //   'book_name' => 'السيف الأزرق',
                'book_name' => 'Blue sword',
                'cover_image' => '/cover_images/saif.jpg',
             //   'abstract' =>'هاري كرو فتاةٌ يتيمة أتَت إلى «دامار»، البلدِ الصحراوي الذي يتشاركه كلٌّ من أهلِ «هوملاند»، وأهلِ أرض التلال الغامضين المعروف عنهم استخدامُهم للسِّحر. كانت حياة «هاري» هادئةً وعادية حتى الليلةِ التي اختطفَها فيها «كورلاث»، ملِكُ أرض التلال',
                'abstract' => 'Harry Crow is an orphan girl who comes to Damar, the desert country shared by both the people of Homeland and the mysterious people of the Hills, who are known to use magic. Harry s life was quiet and normal until the night she was kidnapped by Korlath, King of the Hills',
                'pdf' => Storage::url('pdfs/saif.pdf'),
             //   'author_name' => 'روبن',
                'author_name' => 'Robin',
                'category_name' => 'أطفال',
                'category_name_en' => 'Children',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           [
             //   'book_name' => 'أدوية الجهاز العصبي',
                'book_name' => 'Nervous system',
                'cover_image' => '/cover_images/Ner.jpg',
             //   'abstract' =>'يستكشف لنا الدكتور علي إسماعيل مختلف الأدوية المستخدمة في علاج أمراض الجهاز العصبي، كما يهدف الكتاب إلى توضيح الفهم العميق لهذه الأدوية وفهم كيفية عملها' ,
                'abstract' => 'Dr. Ali Ismail explores for us the various medications used to treat diseases of the nervous system. The book also aims to clarify a deep understanding of these medications and understand how they work.',
                'pdf' => Storage::url('pdfs/Nervous_compressed.pdf'),
           //     'author_name' => 'د.علي اسماعيل',
                'author_name' => 'Dr. Ali Ismail',
                'category_name' =>'صحة' ,
                'category_name_en' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
             //   'book_name' => 'طوق نجاة',
                'book_name' => 'Lifeline',
                'cover_image' => '/cover_images/taooq.jpg',
            //    'abstract'=> 'تُقدِّم «باتي ديفيس» في هذا الكتاب طوقَ نجاةٍ لمقدِّمي الرعاية للمُصابين بداء ألزهايمر؛ حيث إنه نِتاج الخبرات العديدة المتراكِمة لديها على مدى عَقدٍ كامل من إصابة والدها' ,
                'abstract'=>'In this book, Patti Davis provides a lifeline for caregivers of people with Alzheimer s disease. As it is the result of the many experiences she has accumulated over a full decade after her father - the late US President Ronald Reagan - was afflicted with this disease, and her establishment of a support group aimed at providing assistance and guidance to caregivers of Alzheimer s patients and their families.',
                'pdf' => Storage::url('pdfs/taooq.pdf'),
            //    'author_name' => 'باتي' ,
                'author_name' => 'Patty',
                'category_name' =>'صحة' ,
                'category_name_en' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
             //   'book_name' => 'القلق',
                'book_name' => 'Anxiety',
                'cover_image' => '/cover_images/qalaq.jpg',
             //   'abstract'=> 'هل نولَد بمَخاوفنا أم نتعلَّمها؟ وما وظيفة القلق؟ وماذا يحدث في أدمغتنا عندما نشعر بالخوف؟ وما علاجاتُه الأكثر فاعلية؟ يقدِّم هذا الكتاب من سلسلة «مقدِّمة قصيرة جدًّا» تعريفًا بسيطًا للقلق، مستندًا إلى أفضل الأبحاث العلمية' ,
                'abstract'=>'Are we born with our fears or do we learn them? What is the function of anxiety? What happens in our brains when we feel fear? What are the most effective treatments? This book from the “A Very Short Introduction” series provides a simple definition of anxiety, based on the best scientific research.',
                'pdf' => Storage::url('pdfs/qalaq.pdf'),
           //     'author_name' =>'دانيال',
                'author_name' => 'Daniel',
                'category_name' => 'صحة',
                'category_name_en' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            //    'book_name' => 'شفاء',
                'book_name' => 'Healing',
                'cover_image' => '/cover_images/sefaa.jpg',
            //    'abstract'=>'هل تستطيع عقولُنا شفاءَ أجسادِنا؟ إنه السؤال الذي يدور حولَه هذا الكتاب الذي يُمثِّل رحلةً لاستكشاف الأسباب وراءَ عدم قُدرة الطب الغربي على علاج العديد من الأمراض، وعجزه عن تخفيف الكثير من الآلام، مع كل ما حقَّقه من تقدُّم. تستكشف الكاتبةُ التمايزَ بين العقل والجسد' ,
                'abstract'=>'Can our minds heal our bodies? This is the question around which this book revolves, which represents a journey to explore the reasons behind Western medicine’s inability to treat many diseases, and its inability to relieve many pains, despite all the progress it has achieved. The author explores the distinction between mind and body that arose in science about 400 years ago, when the French philosopher René Descartes distinguished between what is material that can be studied scientifically, and what is immaterial that cannot be studied scientifically.',
                'pdf' => Storage::url('pdfs/shifaa.pdf'),
           //     'author_name' =>'جو مارشانت',
                'author_name' => 'Joe Marchant',
                'category_name' => 'صحة',
                'category_name_en' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
          //      'book_name' =>'الاكسير',
                'book_name' => 'Elixir',
                'cover_image' => '/cover_images/hxer.jpg',
        //        'abstract'=> 'يَتناوَلُ هَذا الكِتابُ العَلاقةَ الإِنسانِيةَ فِي الشَّأنِ الطِّبيِّ بِطَريقةٍ أَدبيَّة، ويَسعَى إلى «أَنْسنةِ» غُرفةِ العَملِياتِ، وجِهازِ التَّخدِير، وغَازاتِ التَّخدِير، كَما يُسلِّطُ الضَّوءَ عَلى كَيفِيةِ الاسْتِفادةِ مِن مِيراثٍ إِنسَانيٍّ طَويلٍ مِنَ الحِكَايَاتِ والأَساطِير' ,
                'abstract'=>'It is a writing that combines my private experiences with general ones. It contains leaks of the secrets of the Temple of Bing and references to others. ',
                'pdf' => Storage::url('pdfs/ixer.pdf'),
          //      'author_name' => 'أحمد سعد',
                'author_name' => 'Ahmed Saad',
                'category_name' => 'صحة',
                'category_name_en' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            
            [
          //      'book_name' =>'رفع الهمة لبلوغ القمة' ,
               'book_name' => 'Raise your resolve',
                'cover_image' => '/cover_images/Raise.jpg',
          //      'abstract' => 'ينتاب المرء من حين لآخر بعض الخوف من المجهول ،ولا سيما لو كان هذا الشخص ضعيف الإيمان ومن العصاة لربهم ،فتراه ينتفض لأتفه الأسباب ويرتعد لصوت حفيف الأشجار، ويموت قلقاً من خرير الماء ' ,
                'abstract' => 'From time to time, a person experiences some fear of the unknown, especially if this person has weak faith and is disobedient to their Lord.',
                'pdf' => Storage::url('pdfs/Raise.pdf'),
          //      'author_name' =>'سيد أحمد أمين',
                'author_name' => 'Sayed Ahmed',
                'category_name' =>'تطوير ذات' ,
                'category_name_en' => 'Self development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
        //        'book_name' =>'ما يؤلمك يعلمك' ,
                'book_name' => 'What hurts u teaches u',
                'cover_image' =>'/cover_images/hurt.jpg',
        //        'abstract' => 'مجموعة من النصائح المستوحاة من نظرتي الخاصة إلى الحياة و من بعض التجارب الشخصية عن الألم و كيف يمكن أن يكون درسا و حافزا للتقدم للأمام بدل الاستسلام' ,
                'abstract' => 'A collection of advice inspired by my own outlook on life and some personal experiences about pain and how it can be a lesson ',
                'pdf' => Storage::url('pdfs/Hurt_compressed.pdf'),
         //       'author_name' => 'دوبي بونوة' ,
                'author_name' => 'Dobby Bonwa',
                'category_name' =>'تطوير ذات' ,
                'category_name_en' => 'Self development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            //    'book_name' =>'فن اللامبالاة' ,
                'book_name' => 'The art of indifference',
                'cover_image' => '/cover_images/lamubalat.jpg',
            //    'abstract' =>'يستكشف فكرة أننا غالبًا ما نبالغ في العطاء في علاقاتنا ومع الأشخاص الذين لا يستحقون ذلك. يقدم الكتاب نصائح حول كيفية وضع الحدود وكيفية رفضها وكيفية التركيز على العطاء لمن يستحقها حقًا' ,
                'abstract' => 'Explores the idea that we often over-give in our relationships and with people who dont deserve it',
                'pdf' => Storage::url('pdfs/indifference_compressed.pdf'),
            //    'author_name' =>'مارك مانسون' ,
                'author_name' => 'Mark Manson',
                'category_name' =>'تطوير ذات' ,
                'category_name_en' => 'Self development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
          //      'book_name' =>'نظرية الفستق',
                'book_name' => 'Pistachio theory',
                'cover_image' => '/cover_images/fustoq.jpg',
           //     'abstract' =>'هو أحد كتب التنمية البشرية وتطوير الذات، الذي يتضمن عدد كبير من المقالات التي تتحدث كيفية تطوير الذات وتحسين طرق التفكير وزيادة الوعي لدى الأشخاص',
                'abstract' => 'It is one of the books on human development and self-development, which includes a large number of articles that talk about how to develop oneself',
                'pdf' => Storage::url('pdfs/Pistachio_compressed.pdf'),
           //     'author_name' =>'فهد عامر',
                'author_name' => 'Fahd Amer',
                'category_name' =>'تطوير ذات' ,
                'category_name_en' => 'Self development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
         //       'book_name' => 'أشهى الحلوبات' ,
                'book_name' => 'delicious sweets',
                'cover_image' => '/cover_images/maake.jpg',
          //      'abstract' =>'كتاب تعلم صنع الحلويات',
                'abstract' => 'A book for learning to make sweets',
                'pdf' => Storage::url('pdfs/sweets_compressed.pdf'),
            //    'author_name' =>'السيدة بو حامد',
                'author_name' => 'Mrs. Bou Hamed',
                'category_name' =>'طبخ' ,
                'category_name_en' => 'Cooking',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
           //     'book_name' => 'المآكل الدمشقية',
                'book_name' => 'Damascene cuisine',
                'cover_image' => '/cover_images/ashha.jpg',
            //    'abstract'=> 'اشتُهِرَ العَصرُ العَبَّاسيُّ بأنَّهُ عَصرُ تَرَفٍ ورُقِي ، فاهْتَمُّوا بإِقامةِ الاحْتِفالاتِ الباذِخةِ والوَلائِمِ العَظِيمة، الَّتِي تُقدَّمُ فِيها أَلْوانُ الطَّعامِ الفاخِرةِ الَّتِي صنَعَها طبَّاخُونَ حاذِقُونَ لمِهْنتِهِم',
                'abstract'=>'The Abbasid era was famous for being an era of luxury and sophistication. The sciences and arts advanced, the area of the state expanded, and the situation for its rulers stabilized, so they paid attention to the arts and forms of creativity. ',
                'pdf' => Storage::url('pdfs/cooking.pdf'),
          //      'author_name' =>'محمد بن الحسن',
                'author_name' => 'Muhammad bin Al-Hassan',
                'category_name' =>'طبخ' ,
                'category_name_en' => 'cooking',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
            //    'book_name' => 'قمر' ,
                'book_name' => 'Moon',
                'cover_image' => '/cover_images/moon.jpg',
           //     'abstract' =>'عندما تُقدَّر قيمة الإنسان بحسابِ المادة.. عندما تُلغى - تماماً- أي حساباتٍ أخرى متعلِّقة بآدميته وإنسانيته .. حينها.. يُسحَق كُلّ مَن هُم خارج نطاق تلك الحسابات الفَذَّة',
                'abstract' => 'When a persons value is estimated based on matter... when any other calculations related to his humanity and humanity are completely cancelled',
                'pdf' => Storage::url('pdfs/Moon_compressed.pdf'),
          //      'author_name' =>'نور عزام',
                'author_name' => 'Nour Azzam',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'Novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
           //     'book_name' => 'الجزيرة الغامضة' ,
                'book_name' => 'Mysterious island',
                'cover_image' => '/cover_images/aljaseatfal.jpg',
         //       'abstract' =>'تدور القصة حول 6 أسرى حرب حاولوا الهرب بمنطاد ليصلوا إلى جزيرة غير مأهولة في منتصف المحيط جانب أستراليا',
                'abstract' => 'The story revolves around 6 prisoners of war who tried to escape by hot air balloon and reached an uninhabited island in the middle of the ocean next to Australia.',
                'pdf' => Storage::url('pdfs/island_compressed.pdf'),
           //     'author_name' =>'جول فيرن',
                'author_name' => 'Jules Verne',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
         //       'book_name' => 'أرض زيكولا',
                'book_name' => 'Zikola land',
                'cover_image' => '/cover_images/zekola.jpg',
              //  'abstract' => 'تقدم القصة شخصية رئيسية تُدعى "خالد"، وهو شاب يعيش في زيكولا. في هذا العالم، يُجبر السكان على المشاركة في مباريات خطيرة تسمى "المباريات السنوية"، والتي يتعين على الخاسر فيها أن يُقتل',
                'abstract' => 'The story introduces a main character named "Khaled", a young man who lives in Zekola. In this world',
                'pdf' => Storage::url('pdfs/zekola_compressed.pdf'),
             //   'author_name' =>'عمرو عبد الحميد',
                'author_name' => 'Amr Abdel Hamid',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
           //    'book_name' => 'القصر',
                'book_name' => 'The palace',
                'cover_image' => '/cover_images/alqaser.jpg',
             //   'abstract' => 'تنتمي هذه الرواية إلى أدب «كافكا» الذي يتَّسم بالسخرية والمزج بين المعقول واللامعقول، والرمزية التي يكشف من خلالها عن الكثير من سقطات الإنسان في هوَّة الخوف وانعدام القِيمة',
                'abstract'=>'This novel belongs to Kafka s literature, which is characterized by sarcasm, a mixture of the reasonable and the unreasonable, and symbolism through which he reveals many of man s falls into the abyss of fear and lack of value. ',
                'pdf' => Storage::url('pdfs/qaser.pdf'),
            //    'author_name' => 'فرانتس كافكا',
                'author_name' => 'Franz Kafka',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
             //   'book_name' =>'الذرة الرفيعة الحمراء',
                'book_name' => 'Red sorghum',
                'cover_image' => '/cover_images/alzara.jpg',
             //   'abstract' => 'في حقول الذُّرَة الرفيعة الحمراء وحولها في قرية «دونغ بيي» تَدور أحداث هذه الرواية الخلَّابة المنتمية إلى تيار الواقعية السِّحرية؛ إذ تأخذنا في عالَم مليء بالغرائبية',
                'abstract'=>'In and around the fields of red sorghum in the village of Dong Bi, the events of this picturesque novel belonging to the trend of magical realism take place. As it takes us into a world full of strangeness',
                'pdf' => Storage::url('pdfs/tharra.pdf'),
             //   'author_name' =>'مو يان',
                'author_name' => 'Mo Yan',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
           //     'book_name' => 'حكاية مملة',
                'book_name' => 'Boring story',
                'cover_image' => '/cover_images/momele.jpg',
             //   'abstract' => 'بلغة انسانية مشحونة بأدق تفاصيل الحياة اليومية يسرد استاذ جامعي يبلغ من العمر اثنين وستين عاما كيف وصلت علاقته مع زوجته الى الفتور',
                'abstract'=>'In a human language filled with the smallest details of daily life, Chekhov narrates the life of Nikolai Stepanovich, a prominent university professor who is sixty-two years old. He lives among his family, which consists of his wife',
                'pdf' => Storage::url('pdfs/boring.pdf'),
            //    'author_name' =>'أنطوان تشيخوت',
                'author_name' => 'Antoine Chekhov',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
             //   'book_name' =>'عدالة الانسة ريم',
                'book_name' => 'Miss Reem s justice',
                'cover_image' => '/cover_images/adalew.jpg',
              //  'abstract' => 'بين عشيةٍ وضحاها، تجد الآنسة «بيم» نفسَها قد أصبحت من المشاهير؛ فكتابها الذي يحمل عنوان «خواطر في علم النفس» أضحى مثارَ اهتمام الكثيرين، وتصدَّر مبيعات الكتب المتخصِّصة',
                'abstract'=>'Overnight, Miss Pim finds herself a celebrity. Her book, titled “Thoughts on Psychology,” has become of interest to many, and has topped the sales of specialized books. ',
                'pdf' => Storage::url('pdfs/adale.pdf'),
             //   'author_name' =>'جوزفين تاي',
                'author_name' => 'Josephine Tai',
                'category_name' =>'روايات وقصص' ,
                'category_name_en' => 'novels and stories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
           //     'book_name' =>'صانع النجوم',
                'book_name' => 'Star maker',
                'cover_image' => '/cover_images/saneanog.jpg',
            //    'abstract' => 'تصف هذه الرواية شكل الحياة في الكون على مدار التاريخ،، وهي تزخر بتصورات للأنواع التي تسكن هذا الكون، وأشكال العوالم التي تبنيها، والنُّهُج التي تتبعها في التفكير والحياة',
                'abstract' => 'This novel describes the form of life in the universe throughout history, and it is full of perceptions of the species that inhabit this universe',
                'pdf' => Storage::url('pdfs/Stars_compressed.pdf'),
           //     'author_name' =>'أولاف ستبلدون',
                'author_name' => 'Olaf Stabaldon',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
            //    'book_name' =>'الزيارد المدهشة',
                'book_name' => 'The most amazing visit',
                'cover_image' => '/cover_images/modhishvisit.jpg',
             //   'abstract' => 'في ظروف غريبة، يحطُّ مَلاكٌ على الأرض، فيتلقَّفه أحد كَهَنة الكنيسة، ويُؤويه في مسكنه ويتعهَّده بالرعاية، ويبدأ في تعريفه بعالم البشر',
                'abstract' => 'Under strange circumstances, an angel lands on Earth.',
                'pdf' => Storage::url('pdfs/visit_compressed.pdf'),
              //  'author_name' =>'هربرت جورج',
                'author_name' => 'Herbert George',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
              //  'book_name' =>'العالم الطريف',
                'book_name' => 'The funny world',
                'cover_image' => '/cover_images/funny.jpg',
             //   'abstract' =>'البِناءُ منخفِضٌ متِينٌ رماديُّ اللَّون، يتكوَّنُ من أربعةٍ وثلاثينَ طابقًا فحَسْب، وقد كُتِبتْ على مَدخلِه الرئيسيِّ هذهِ العِبارة: «مَركزُ لندنَ للتَّفريخِ والتَّكييف»، كما كُتِبَ على إحدى اللَّوحاتِ شعارُ الحكومةِ العالميَّة، وهُو: «الجَماعة، والتشابُه، والاستقرار',
                'abstract' => 'The building is low, sturdy, gray in color, consisting of only thirty-four floors.',
                'pdf' => Storage::url('pdfs/funny_compressed.pdf'),
           //     'author_name' =>'هلدوس ألكسي',
                'author_name' => 'Heldus Alexei',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
           //     'book_name' =>'هالو',
                'book_name' => 'Halo',
                'cover_image' => '/cover_images/halo.jpg',
             //   'abstract' =>'تقدِّم هذه الرواية مزيجًا من الواقع الافتراضي والذكاء الاصطناعي والفلسفة الروحانية؛ حيث يرسم المؤلِّف خريطةً لتطوُّرِ حاسوبٍ ذكي بفضل اكتسابه الوعيَ الذاتي',
                'abstract'=>'This novel offers a combination of virtual reality, artificial intelligence, and spiritual philosophy; The author draws a map of the development of an intelligent computer thanks to its acquisition of self-awareness',
                'pdf' => Storage::url('pdfs/Halo.pdf'),
           //     'author_name' =>'توم مادوكس',
                'author_name' => 'Tom Maddox',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
          //      'book_name' =>'قصة الطوفان',
                'book_name' => 'The story of the flood',
                'cover_image' => '/cover_images/tofan.jpg',
          //      'abstract' =>'يَذكُرُ السيدُ «جاكوب راوندز»، الأمينُ المساعِدُ في المتحَفِ البريطاني، في خِطابٍ خاصٍّ أرسلَهُ إلى أحدِ المُستشرِقِين بعضَ التَّفاصِيلِ المُثيرةِ بشأْنِ مَخْطوطةٍ قديمةٍ يَعُودُ تاريخُها إلى الحَضارةِ الآشُورِيَّة',
                'abstract'=>'In a private letter he sent to an orientalist, Mr. Jacob Rounds, Assistant Curator at the British Museum, mentioned some exciting details about an ancient manuscript dating back to the Assyrian civilization',
                'pdf' => Storage::url('pdfs/flood.pdf'),
          //      'author_name' =>'إدوارد',
                'author_name' => 'Edward',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
         //       'book_name' =>'مهندسو الخيال',
                'book_name' => 'Imagination engineers',
                'cover_image' => '/cover_images/muhandiso.jpg',
           //     'abstract' =>'وفجأةً تَبرُق في أذهاننا فكرةٌ ربما كانت غريبة، ربما كانت شاذَّة؛ هل يكتفي الفضاء بأن يُرسِل إلى الأرض تلك الصخورَ المشتعلة التي تأتينا من حينٍ لآخر',
                'abstract'=>'Suddenly an idea flashed into our minds, perhaps it was strange, perhaps it was abnormal; Is space enough to send to Earth those burning rocks that come to us from time to time?',
                'pdf' => Storage::url('pdfs/Imagination.pdf'),
           //     'author_name' =>'ياسر أبو حسب',
                'author_name' => 'Yasser Abu Al-Hasab',
                'category_name' =>'خيال علمي' ,
                'category_name_en' => 'Science fiction',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
          //      'book_name' =>'تاريخ الأندلس',
                'book_name' => 'History of Andalusian',
                'cover_image' => '/cover_images/andalus.jpg',
           //     'abstract' =>'يتحدث الكتاب عن الحضارة الأندلسة العظيمة ',
                'abstract' => 'The book talks about the great Andalusian civilization.',
                'pdf' => Storage::url('pdfs/Andalusian_compressed.pdf'),
         //       'author_name' =>'إحسان عباس',
                'author_name' => 'Ihsan Abbas',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
          //      'book_name' =>'موجز تاريخ التاريخ',
                'book_name' => 'Brief history of the world',
                'cover_image' => '/cover_images/mojastare.jpg',
         //       'abstract' =>'عرض هذا الكتاب بعبارة موجزة تاريخ العالم منذ أقدم حقب الحياة وحتى القرن العشرين',
                'abstract' => 'This book briefly presented the history of the world from the earliest eras to the twentieth century.',
                'pdf' => Storage::url('pdfs/world_compressed.pdf'),
            //    'author_name' =>'هربرت جورج',
                'author_name' => 'Herbert George',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
         //       'book_name' =>'رحلة حنّون',
                'book_name' => 'Hanoun journey',
                'cover_image' => '/cover_images/hanon.jpg',
           //     'abstract' =>'وُجِّهت رحلات كثيرة إلى قرطاج لاستكشافها، وخاصةً في عهد الفينيقيين، إلا أن أخبار هذه الرحلات ووقائعها لم يصل إلينا ',
                'abstract'=>'Many trips were made to Carthage to explore it, especially during the era of the Phoenicians, but very little news and facts about these trips have reached us.',
                'pdf' => Storage::url('pdfs/Hanoun.pdf'),
          //      'author_name' =>'عبد المنعم المحجوب',
                'author_name' => 'Abdel Moneim Al-Mahjoub',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
           //     'book_name' =>'خطباء اليونان',
                'book_name' => 'Greek preachers',
                'cover_image' => '/cover_images/yonan.jpg',
             //   'abstract' =>'تحتلُّ الخطابة مكانة متميِّزة في الثقافة الإغريقية القديمة؛ إذ عُرف الإغريق بفصاحة اللسان، فظهر بينهم كثيرٌ من الخطباء الذين احتلُّوا مكانة بارزة في المجتمع اليوناني',
                'abstract'=>'Rhetoric occupies a distinguished place in ancient Greek culture. As the Greeks were known for their eloquence, many orators appeared among them who occupied a prominent position in Greek society.',
                'pdf' => Storage::url('pdfs/Greek_preachers.pdf'),
              //  'author_name' =>'ديبسون',
                'author_name' => 'Debson',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
             //   'book_name' =>'علم الآثار',
                'book_name' => 'Archeology',
                'cover_image' => '/cover_images/athar.jpg',
             //   'abstract' =>'ستعرض الكتاب الاكتشافات الأثرية والتفسيرات الحديثة في هذا المجال، ويسلِّط الضوء على تأثير التطوُّرات العلمية والتكنولوجيا والعلم في مجال الاستكشاف الأثري',
                'abstract'=>'The book will present recent archaeological discoveries and interpretations in this field, and highlight the impact of scientific developments, technology and science on the field of archaeological exploration.',
                'pdf' => Storage::url('pdfs/archeology.pdf'),
            //    'author_name' =>'بول بان',
                'author_name' => 'Paul Ban',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
            //    'book_name' =>'الأبيض المتوسط',
                'book_name' => 'Mediterranean',
                'cover_image' => '/cover_images/alabyad.jpg',
             //   'abstract' =>'البحر الأبيض المتوسط معجزة. عند رؤيته على الخريطة، ربما للمرة المليون، نأخذه على عِلَّاته، أمَّا عند النظر إليه نظرةً موضوعية، نكتشف فجأةً أن هناك شيئًا فذًّا فريدًا، وكأن هذا الكيانَ المائي قد صُمِّم عمداً',
                'abstract'=>'The Mediterranean is a miracle. When we see it on a map, perhaps for the millionth time, we take it as it is, but when we look at it objectively, we suddenly discover that there is something unique...unique, as if this water entity was designed deliberately, carefully',
                'pdf' => Storage::url('pdfs/Mediterranean.pdf'),
             //   'author_name' =>'جون جوليوس',
                'author_name' => 'John Julius',
                'category_name' =>'تاريخ' ,
                'category_name_en' => 'History',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
           //     'book_name' =>'حياتي في رحلاتي',
                'book_name' => 'My life in my travels',
                'cover_image' => '/cover_images/rehelate.jpg',
            //    'abstract' =>'جولةٌ سريعة تجمَع بين المتعة الذهنية والفائدة الثقافية والتسلية الروحية تَقضيها مع الأستاذ «أمين سلامة»، الذي حرص على تدوين كل ما شَهِده في رحلاته التي قام بها إلى فرنسا التي تُمثِّل مَعقِلًا خطيرًا من معاقل الحضارة الأوروبية الحديثة، وإلى إسبانيا ',
                'abstract'=>'A quick tour that combines mental enjoyment, cultural benefit, and spiritual entertainment. You spend it with Professor Amin Salama, who was keen to write down everything he witnessed in his trips to France, which represents a dangerous stronghold of modern European civilization, and to Spain',
                'pdf' => Storage::url('pdfs/life_travel.pdf'),
            //    'author_name' =>'أمين سلامة',
                'author_name' => 'Amen Salama',
                'category_name' =>'سفر' ,
                'category_name_en' => 'Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
              //  'book_name' =>'الطريق الى اوكسيانا',
                'book_name' => 'The road to Oxiana',
                'cover_image' => '/cover_images/ox.jpg',
           //     'abstract' =>'يعكس هذا الكتاب عصرَه من حيث الأسلوب والمحتوى اللذان يستعين بهما «بايرون» ليقدِّم لنا صورةً حية لبلاد «فارس» و«أفغانستان» القديمة، بما تمتلكان من سِحر الطبيعة والتاريخ والفن. وبالإضافة إلى قِيمته الترفيهية',
                'abstract'=>'This book reflects its era in terms of the style and content that Byron uses to present to us a vivid picture of ancient Persia and Afghanistan, with their magic of nature, history, and art. In addition to its entertainment value',
                'pdf' => Storage::url('pdfs/Oxiana.pdf'),
             //   'author_name' =>'روبرت بايرون',
                'author_name' => 'Robert Byron',
                'category_name' =>'سفر' ,
                'category_name_en' => 'Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
              //  'book_name' =>'اليونان',
                'book_name' => 'Greece',
                'cover_image' => '/cover_images/yonan.jpg',
            //    'abstract' =>'لا يسَع زائر «اليونان» إلا أن يقعَ في هواها منذ اليوم الأول لزيارتها',
                'abstract'=>'A visitor to Greece cannot help but fall in love with it from the first day of his visit. ',
                'pdf' => Storage::url('pdfs/Greece.pdf'),
             //   'author_name' =>'فرج جبران',
                'author_name' => 'Faraj Gibran',
                'category_name' =>'سفر' ,
                'category_name_en' => 'Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
              //  'book_name' =>'رحلة مشعل',
                'book_name' => 'Mashals journey',
                'cover_image' => '/cover_images/moshaal.jpg',
             //   'abstract' =>'الحج هو الشعيرة الأكثر جذبًا للاهتمام، سواءٌ للمسلمين أو لأتباع المذاهب الفكرية والديانات الأخرى',
                'abstract'=>'Hajj is the ritual that attracts the most attention, both to Muslims and followers of other schools of thought and religions. ',
                'pdf' => Storage::url('pdfs/Mashaljourney.pdf'),
             //   'author_name' =>'محمد باشا',
                'author_name' => 'Mohammed Pasha',
                'category_name' =>'سفر' ,
                'category_name_en' => 'Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ], [
             //   'book_name' =>'الأمتعة',
                'book_name' => 'Luggage',
                'cover_image' => '/cover_images/amteaa.jpg',
             //   'abstract' =>'لا جدالَ في أنه من الصَّعب العيش من دون أمتعة. وفي هذا الكتاب الخفيف، تأخذنا الكاتبةُ «سوزان هارلان» في رحلةٍ مع الحقائب التي تَدعَم حياتنا، وتُكملها، وترافقنا فيها',
                'abstract'=>'There is no doubt that it is difficult to live without belongings. In this light book, author Susan Harlan takes us on a journey with the bags that support our lives, complete them, and accompany us in them.',
                'pdf' => Storage::url('pdfs/Luggage.pdf'),
               // 'author_name' =>'سوزان هارلان',
                'author_name' => 'Susan Harlan',
                'category_name' =>'سفر' ,
                'category_name_en' => 'Travel',
                'created_at' => now(),
                'updated_at' => now(),
            ], 
            /*[
                'book_name' =>'طوق النجاة',
                'book_name' => 'Lifeline',
                'cover_image' => '/storage/cover_images/1715895677.jpg',
                'abstract'=>'',
                'pdf' => '/storage/pdfs/1715895677.pdf',
                'author_name' =>'',
                'author_name' => 'Dr',
                'category_name' => 'Health',
                'created_at' => now(),
                'updated_at' => now(),
            ], */

        ];
        
        foreach ($books as $book) {
            $author = Author::firstOrCreate([
                'author_name' => $book['author_name'],
            ]);
       
            $category = Category::firstOrCreate([
                'category_name' => $book['category_name'],
               // 'category_name_en' => $book['category_name_en'],
               'category_name_en' => $book['category_name_en'] ?? $book['category_name'],
            ]);
       
            Book::firstOrCreate([
                'book_name' => $book['book_name'],
                'cover_image' => $book['cover_image'],
                'abstract' => $book['abstract'],
                'pdf' => $book['pdf'],
                'author_id' => $author->id, 
                'category_id' => $category->id, 
            ]);

            }
        }
        
    }


